export const apps = {
  logo: "/logo.png",
  full_name: "Perkumpulan Perawat Pembaharuan Indonesia",
  short_name: "PPPI",
  payment_methods: [
    "Cash",
    "Transfer",
    "Cek/BG",
    // "Kartu Debit",
    // "Kartu Kredit",
  ],
  banks: [
    { code: "002", name: "Bank Rakyat Indonesia (BRI)" },
    { code: "008", name: "Bank Mandiri" },
    { code: "009", name: "Bank Negara Indonesia (BNI)" },
    { code: "014", name: "Bank Central Asia (BCA)" },
    { code: "022", name: "Bank CIMB Niaga" },
    { code: "011", name: "Bank Danamon" },
    { code: "013", name: "Bank Permata" },
    { code: "028", name: "Bank OCBC NISP" },
    { code: "042", name: "Bank BTN" },
    { code: "016", name: "Bank Maybank Indonesia" },
    { code: "019", name: "Bank Panin" },
    { code: "451", name: "Bank Syariah Indonesia (BSI)" },
    { code: "147", name: "Bank Muamalat" },
    { code: "213", name: "Bank BTPN" },
    { code: "547", name: "Bank Jago (Digital)" },
    { code: "490", name: "Bank Neo Commerce (Digital)" },
    { code: "513", name: "Bank Allo (Digital)" },
    { code: "553", name: "SeaBank Indonesia (Digital)" },
    { code: "110", name: "Bank Jabar Banten (BJB)" },
    { code: "111", name: "Bank DKI" },
    { code: "114", name: "Bank Jatim" },
    { code: "112", name: "Bank Jateng" },
    { code: "031", name: "Bank Citibank" },
    { code: "037", name: "Bank Artha Graha" },
    { code: "050", name: "Standard Chartered Bank" },
    { code: "052", name: "Bank ABN Amro" },
    { code: "023", name: "Bank UOB Indonesia" },
    { code: "087", name: "Bank HSBC Indonesia" },
    { code: "950", name: "Bank Commonwealth" },
    { code: "426", name: "Bank Mega" },
  ],
};

export const educations = ["D3", "S1", "NERS", "S2", "SPECIALIS", "S3"];
