export const navigation = [
  {
    title: "Dashboard",
    i18nKey: "nav.dashboard",
    href: "/",
    icon: "SquareTerminal",
    isActive: true,
    permissions: ["dashboard.view"],
  },
  {
    title: "Kasir",
    i18nKey: "nav.cashier",
    href: "/cashier",
    icon: "ShoppingCart",
    isActive: true,
    permissions: ["payment.create", "payment.view"],
  },
  {
    title: "Booking",
    i18nKey: "nav.booking",
    href: "/booking",
    icon: "Book",
    isActive: true,
    permissions: ["wo.create"],
  },
  {
    header: "Transaksi Utama",
    i18nKey: "nav.trx.header",
    href: "/service",
    icon: "ClipboardList",
    permissions: ["wo.view"],
    items: [
      {
        title: "Pendaftaran Servis",
        i18nKey: "nav.trx.registration",
        href: "add",
        icon: "PlusCircle",
        roles: ["super-admin", "sa", "owner"],
        permissions: ["wo.create"],
      },
      {
        title: "Antrean Bengkel",
        i18nKey: "nav.trx.workshop_queue",
        href: "queue",
        icon: "LayoutList",
        permissions: ["wo.view", "wo.create", "wo.update", "wo.delete"],
      },
      {
        title: "Antrean Mandiri",
        i18nKey: "nav.trx.self_queue",
        href: "self-queue",
        icon: "Ticket",
        permissions: ["wo.view", "wo.create", "wo.update"],
      },
      {
        title: "Riwayat Servis",
        i18nKey: "nav.trx.history",
        href: "history",
        icon: "History",
        permissions: ["wo.view"],
      },
      {
        title: "Jasa divendorkan",
        i18nKey: "nav.trx.vendor",
        href: "vendor-transaction",
        icon: "Handshake",
        permissions: ["wo.view"],
      },
    ],
  },
  {
    header: "Layar Antrean",
    i18nKey: "nav.screen.header",
    href: "/queue",
    icon: "MonitorPlay",
    permissions: ["wo.view", "wo.create", "wo.update"],
    items: [
      {
        title: "Kiosk Pelanggan",
        i18nKey: "nav.screen.kiosk",
        href: "/queue/kiosk",
        icon: "Ticket",
        external: true,
        permissions: ["wo.view", "wo.create", "wo.update"],
      },
      {
        title: "Display Antrean (TV)",
        i18nKey: "nav.screen.display",
        href: "/queue/display",
        icon: "MonitorPlay",
        external: true,
        permissions: ["wo.view", "wo.create", "wo.update"],
      },
      {
        title: "Display Status Service (TV)",
        i18nKey: "nav.screen.service_display",
        href: "/service/display",
        icon: "Car",
        external: true,
        permissions: ["wo.view", "wo.create", "wo.update"],
      },
    ],
  },
  {
    roles: ["super-admin", "partsman", "owner"],
    header: "Pembelian Sparepart",
    i18nKey: "nav.purchase.header",
    href: "/purchase",
    icon: "Package",
    permissions: ["purchase-order.view", "purchase-order.manage"],
    items: [
      {
        title: "Order Pembelian",
        i18nKey: "nav.purchase.po",
        href: "po",
        icon: "Box",
      },
      {
        title: "Faktur Pembelian",
        i18nKey: "nav.purchase.invoice",
        href: "invoice",
        icon: "FileText",
      },
    ],
  },
  {
    roles: ["super-admin", "partsman", "owner"],
    header: "Inventaris Sparepart",
    i18nKey: "nav.inventory.header",
    href: "/inventory",
    icon: "Package",
    permissions: ["product.view", "product.stock", "product.manage"],
    items: [
      {
        title: "Stok Barang",
        i18nKey: "nav.inventory.stock",
        href: "stock",
        icon: "Boxes",
      },
      {
        title: "Kategori Produk",
        i18nKey: "nav.inventory.categories",
        href: "categories",
        icon: "Tags",
      },
    ],
  },
  {
    roles: ["super-admin", "owner", "cro"],
    header: "Data Master",
    i18nKey: "nav.master.header",
    href: "/master",
    icon: "CarFront",
    permissions: ["master.manage"],
    items: [
      {
        title: "Data Pelanggan",
        i18nKey: "nav.master.customers",
        href: "customers",
        icon: "Users",
        permissions: ["customer.view", "customer.manage"],
      },
      {
        title: "Data Kendaraan",
        i18nKey: "nav.master.vehicles",
        href: "vehicles",
        icon: "Car",
        permissions: ["customer.view", "customer.manage"],
      },
      // {
      //   title: "Data Mekanik",
      //   href: "mechanics",
      //   icon: "Wrench",
      //   roles: ["super-admin", "owner"],
      // },
      {
        title: "Daftar Jasa Servis",
        i18nKey: "nav.master.services",
        href: "services",
        icon: "ClipboardList",
        roles: ["super-admin", "owner", "partsman"],
      },
      {
        title: "Supplier",
        i18nKey: "nav.master.suppliers",
        href: "suppliers",
        icon: "Truck",
        roles: ["super-admin", "owner", "partsman"],
      },
      {
        title: "Gudang",
        i18nKey: "nav.master.warehouses",
        href: "warehouses",
        icon: "Building2",
        roles: ["super-admin", "owner", "partsman"],
      },
    ],
  },
  // {
  //   roles: ["super-admin", "owner", "cashier"],
  //   header: "Keuangan",
  //   href: "/finance",
  //   permissions: ["report.manage"],
  //   icon: "Receipt",
  //   items: [
  //     { title: "Daftar (Invoicing)", href: "list", icon: "FileText" },
  //     { title: "Pengeluaran Operasional", href: "expenses", icon: "Wallet" },
  //   ],
  // },
  {
    roles: ["super-admin", "owner"],
    header: "Laporan",
    i18nKey: "nav.reports.header",
    href: "/reports",
    permissions: ["report.manage"],
    icon: "FileBarChart",
    items: [
      {
        title: "Laporan Pendapatan",
        i18nKey: "nav.reports.revenue",
        href: "revenue",
        icon: "TrendingUp",
      },
      {
        title: "Performa Mekanik",
        i18nKey: "nav.reports.mechanics",
        href: "mechanics",
        icon: "Award",
      },
      {
        title: "Barang Terlaris",
        i18nKey: "nav.reports.top_parts",
        href: "top-parts",
        icon: "BarChart3",
      },
      {
        title: "Pelanggan Sering Service",
        i18nKey: "nav.reports.frequent_customers",
        href: "frequent-customers",
        icon: "Users",
      },
    ],
  },
  {
    roles: ["super-admin", "owner"],
    header: "Pengaturan",
    i18nKey: "nav.settings.header",
    href: "/settings",
    icon: "Settings2",
    items: [
      {
        title: "Profil Bengkel",
        i18nKey: "nav.settings.profile",
        href: "profile",
        icon: "Store",
        permissions: ["profile.manage"],
      },
      {
        title: "Notifikasi",
        i18nKey: "nav.settings.notifications",
        href: "notifications",
        icon: "Bell",
        permissions: ["profile.manage"],
      },
      {
        title: "Management Role",
        i18nKey: "nav.settings.roles",
        href: "roles",
        icon: "ShieldAlert",
        permissions: ["role.manage"],
      },
      // {
      //   title: "Whatsapp",
      //   href: "wa",
      //   icon: "MessageSquare",
      // },
    ],
  },
  {
    roles: ["super-admin", "owner", "hrd"],
    header: "Human Resources",
    i18nKey: "nav.hr.header",
    href: "/hr",
    icon: "Users",
    permissions: ["user.manage"],
    items: [
      {
        title: "Data Karyawan",
        i18nKey: "nav.hr.employees",
        href: "employees",
        icon: "UserCircle",
      },
      {
        title: "Absensi Karyawan",
        i18nKey: "nav.hr.attendance",
        href: "attendance",
        icon: "Clock",
      },
      {
        title: "Penggajian Karyawan",
        i18nKey: "nav.hr.payroll",
        href: "payroll",
        icon: "Wallet",
      },
    ],
  },
];
